name: Build

on:
  push:
    branches:
    - main
    
  workflow_dispatch:

jobs:
  Web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
       channel: 'dev'
    - run: flutter pub get
    - uses: erickzanardo/flutter-gh-pages@v3
      with:
        webRenderer: html
        customArgs: --base-href /ImageToPDF/